<a href="https://colab.research.google.com/github/PeterYves/DIC-ML-Assignmnent/blob/main/matrix_product_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### [Problem 1] Matrix product is calculated manually

---

**` QUESTION:`**

A=
  \begin{bmatrix} 
    -1 & 2 & 3 \\\\ 4 & -5 & 6 \\\\ 7 & 8 & -9 
  \end{bmatrix},
  B=
  \begin{bmatrix} 
    0 & 2 & 1 \\\\ 0 & 2 & -8 \\\\ 2 & 9 & -1
  \end{bmatrix}


**`Answering steps:`**

**Step1: Multiplication of every matrix element :**

\begin{bmatrix}
        (-1*0)+(2*0)+(3*2)&(-1*2)+(2*2)+(3*9)&(-1*1)+(2*-8)+(3*-1)\\\\
        (4*0)+(-5*0)+(6*2)&(4*2)+(-5*2)+(6*9)&(4*1)+(-5*-8)+(6*-1)\\\\
        (7*0)+(8*0)+(-9*2)&(7*2)+(8*2)+(-9*9)&(7*1)+(8*-8)+(-9*-1)\\\\
\end{bmatrix}



**Step2: Then the above results into:**

\begin{bmatrix}
        (O+0+6)&(-2+4+27)&(-1-16-3)\\\\
        (O+0+12)&(8-10+54)&(4+40-6)\\\\
        (O+0-18)&(14+16-81)&(7-64+9)\\\\
\end{bmatrix}


**Step3: Then the final answer is:**

\begin{pmatrix}
        6&29&-20\\\\
        12&52&38\\\\
        -18&-51&-48
\end{pmatrix}

### [Problem 2] Calculation by NumPy function

---



In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ab_ndarray = a_ndarray @ b_ndarray # this is the same as writting "np.matmul(a_ndarray,b_ndarray)"

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### [Problem 3] Implementation of calculation of a certain element

---



In [ ]:
sum_of_ab_ndarray = (a_ndarray[1][0]*b_ndarray[0][1])+(a_ndarray[1][1]*b_ndarray[1][1])+(a_ndarray[1][2]*b_ndarray[2][1])
print(sum_of_ab_ndarray)

52


### [Problem 4] Creating a function that performs matrix multiplication

---



In [ ]:
def product_of_matrix(a, b):
    ab_ndarray = np.empty([3,3])
    for row in range(a.shape[0]):
        for column in range(b.shape[1]):
            ab_ndarray[row][column] = sum(a[row, :]*b[:, column])
    return ab_ndarray
print(product_of_matrix(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


### [Problem 5] Judge the input whose calculation is not defined

---



In [ ]:
d_ndarray = np.array([[-1, 2, 3],[4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7],[6, -5, 4]])
if(d_ndarray.shape[0]==e_ndarray.shape[1]):
    print(product_of_matrix(d_ndarray, e_ndarray))
else:
        print("There is a problem with the size of the matrixes, which may result in incorrect calculations.")


There is a problem with the size of the matrixes, which may result in incorrect calculations.


### [Problem 6] Transposition

---



In [ ]:
f_ndarray = d_ndarray.T
print(product_of_matrix(f_ndarray, e_ndarray))

[[ 33. -28.   9.]
 [-48.  41.  -6.]
 [  9.  -6.  45.]]
