<a href="https://colab.research.google.com/github/PeterYves/DIC-ML-Assignmnent/blob/main/week4_object_oriented_utilization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Utilization of object orientation

---



In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("average :", scaler.mean_)
print("variance :", scaler.var_)
X_std = scaler.transform(X)

average : [4.86 3.31 1.45 0.22]
variance : [0.0764 0.0849 0.0105 0.0056]


> ### [Problem 1] Enumeration of classes used so far

---



**Classes that were used in the previous assignments:**

- **For scikit-learn:** StandardScaler, DecisionTreeClassifier, RandomForestClassifier, SVR, LinearRegression, KNeighborsClassifier

- **For Pandas:** DataFrame, Series

- **For matplotlib:** Figure, plt, Axes, 

> ### [Problem 2] Enumeration of methods and instance variables used so far

---



**Methods and instance variables that were used in the code used in the previous assignments:**

- **Methods:** fit(), predict(), title(), xlabel(), legend(), len(), transform(), sum(), mean(), rave(), etc....
- **Instance variables:** ndarray.dtype, ndarray.shape, pd.Series.values, scaler.mean_, scaler.var_, ndarray.data, etc....

> ### [Problem 3] Creating a standardized class by scratch

---



In [2]:
class ScratchStandardScaler():
    """
    Class for standardization
    Attributes
    ----------
    mean_: ndarray, shape (n_features,) of the following form 
    Average
    var_: ndarray, shape (n_features,) of the following form
    Distributed
    """
    def fit (self, X):
        """
        Calculate the mean and standard deviation for standardization.
        Parameters
        ----------
        X: ndarray, shape (n_samples, n_features) of the following form
        Training data
        """
        self.mean_ = np.average(X, axis=0)
        self.var_ = np.var(X, axis=0)
    def transform (self, X):
        """
        Standardize using the value obtained by fit.
        Parameters
        ----------
        X: ndarray, shape (n_samples, n_features) of the following form
        Feature value
        Returns
        ----------
        X_scaled: ndarray, shape (n_samples, n_features) of the following form
        Standardized special amount
        """
        X_scaled = (X - self.mean_)/np.sqrt(self.var_)
        return X_scaled 

In [3]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()

X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)

print("Mean : {}".format(scratch_scaler.mean_))
print("Variance : {}".format(scratch_scaler.var_))

X_std = scratch_scaler.transform(X)
print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


> ### [Problem 4] Creating a class that performs 4 arithmetic operations

---



In [5]:
class ExampleClass():
    """
    A simple class for explanation
    Parameters
    ----------
        value: float or int
            initial value
    Attributes
    ----------
        value: float or int
            Calculation result
    """
    def __init__(self, value):
        if type(value) not in [int, float]:
            raise Exception('The value must be numeric.')
        self.value = value
        print("The initial value is {}:" .format(self.value))
        print("=============================")
    
    def add(self, value2):
        """
        Add the received argument to self.value
        """
        self.value += value2
        
    def sub(self, value2):
        self.value -= value2
        
    def mul(self, value2):
        self.value *= value2
        
    def div(self, value2):
        self.value /= value2

In [9]:
nbr = ExampleClass(10)
nbr.add(1)
print("The sum is : {}".format(nbr.value))
nbr.sub(4)
print("The difference is : {}".format(nbr.value))
nbr.mul(3)
print("The product is : {}".format(nbr.value))
nbr.div(6)
print("The quotient is : {}".format(nbr.value))

The initial value is 10:
The sum is : 11
The difference is : 7
The product is : 21
The quotient is : 3.5


In [10]:
nbr_error = ExampleClass('ten')

Exception: ignored

In [11]:
nbr_err2 = ExampleClass([10, 13, 20])

Exception: ignored